flowchart TD
    net[Network] & detector_db[Detector database] & sim_counts[Simulated link counts] --> simul_diagnostic((simul_diagnostic package)) --> sim_vs_obs[Simulated vs. observed counts analyses]